{% set name = "pyshark" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshark-{{ version }}.tar.gz
  sha256: 8190d2e6939211400bacb40806aae01042824219451ad86ecd7ed5a00d4822b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - py
    - python >=3.6

test:
  imports:
    - pyshark
    - pyshark.capture
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KimiNewt/pyshark
  summary: Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
