{% set name = "pyshark" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshark-{{ version }}.tar.gz
  sha256: a424d83e0ca6224a96bbe30cd3f89d5491654d783faaaf90adaf45867a0bcb17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - lxml
    - py
    - packaging
    - python >=3.6

test:
  imports:
    - pyshark
    - pyshark.capture
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KimiNewt/pyshark
  summary: Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
